import Head from 'next/head'


export default function ContactPage() {

  return (
    <div>
      <Head>
        <title>Learning build Nextjs app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Contact Us</h1>

    </div>
  )
}
